// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./src/button/docs/demo.vue')['default']
    README: typeof import('./src/button/docs/README.md')['default']
    Src: typeof import('./src/button/src/index.vue')['default']
  }
}

export {}
